version: "3"

services:
  nginx:
    container_name: "proxy-frontend"
    image: nginx:stable-alpine
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/server.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/certs
      - ./content/php:/var/www/html
    links:
      - web-1
      - web-2
      - web-3
      - php

  php:
    container_name: "php-fpm"
    image: php:7.1-fpm-alpine
    restart: always
    volumes:
      - ./content/php:/var/www/html

  web-1:
    image: nginx:stable-alpine
    container_name: web-1
    volumes:
      - ./config/web-default.conf:/etc/nginx/conf.d/default.conf
      - ./content/web-1:/var/www/html
    ports:
      - "8081:80"

  web-2:
    image: nginx:stable-alpine
    volumes:
      - ./config/web-default.conf:/etc/nginx/conf.d/default.conf
      - ./content/web-2:/var/www/html
    container_name: web-2
    ports:
      - "8082:80"

  web-3:
    image: nginx:stable-alpine
    volumes:
      - ./config/web-default.conf:/etc/nginx/conf.d/default.conf
      - ./content/web-3:/var/www/html
    container_name: web-3
    ports:
      - "8083:80"
